package ManagementServer;

/**
* ManagementServer/AppointmentTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ManagementServer.idl
* Friday, March 1, 2024 7:32:33 o'clock PM EST
*/

public final class AppointmentTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public ManagementServer.AppointmentType value = null;

  public AppointmentTypeHolder ()
  {
  }

  public AppointmentTypeHolder (ManagementServer.AppointmentType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ManagementServer.AppointmentTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ManagementServer.AppointmentTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ManagementServer.AppointmentTypeHelper.type ();
  }

}
