package ManagementServer;


/**
* ManagementServer/HealthCareSystem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ManagementServer.idl
* Friday, March 1, 2024 7:32:33 o'clock PM EST
*/

public interface HealthCareSystem extends HealthCareSystemOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HealthCareSystem
