package ManagementServer;


/**
* ManagementServer/HealthCareSystem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ManagementServer.idl
* Thursday, February 29, 2024 1:42:55 o'clock PM EST
*/

public interface HealthCareSystem extends HealthCareSystemOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HealthCareSystem
