package ManagementServer;


/**
* ManagementServer/HealthCareSystem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ManagementServer.idl
* Monday, March 4, 2024 10:14:57 o'clock PM EST
*/

public interface HealthCareSystem extends HealthCareSystemOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HealthCareSystem
