package ManagementServer;

/**
* ManagementServer/HealthCareSystemHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ManagementServer.idl
* Friday, March 1, 2024 7:32:33 o'clock PM EST
*/

public final class HealthCareSystemHolder implements org.omg.CORBA.portable.Streamable
{
  public ManagementServer.HealthCareSystem value = null;

  public HealthCareSystemHolder ()
  {
  }

  public HealthCareSystemHolder (ManagementServer.HealthCareSystem initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ManagementServer.HealthCareSystemHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ManagementServer.HealthCareSystemHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ManagementServer.HealthCareSystemHelper.type ();
  }

}
