package ManagementServer;


/**
* ManagementServer/HealthCareSystemPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ManagementServer.idl
* Friday, March 1, 2024 7:32:33 o'clock PM EST
*/

public abstract class HealthCareSystemPOA extends org.omg.PortableServer.Servant
 implements ManagementServer.HealthCareSystemOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addAppointment", new java.lang.Integer (0));
    _methods.put ("removeAppointment", new java.lang.Integer (1));
    _methods.put ("bookAppointment", new java.lang.Integer (2));
    _methods.put ("cancelAppointment", new java.lang.Integer (3));
    _methods.put ("getAppointmentSchedule", new java.lang.Integer (4));
    _methods.put ("listAppointmentAvailability", new java.lang.Integer (5));
    _methods.put ("swapAppointment", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ManagementServer/HealthCareSystem/addAppointment
       {
         String appointmentID = in.read_string ();
         ManagementServer.AppointmentType appointmentType = ManagementServer.AppointmentTypeHelper.read (in);
         int capacity = in.read_long ();
         String $result = null;
         $result = this.addAppointment (appointmentID, appointmentType, capacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // ManagementServer/HealthCareSystem/removeAppointment
       {
         String appointmentID = in.read_string ();
         ManagementServer.AppointmentType appointmentType = ManagementServer.AppointmentTypeHelper.read (in);
         String $result = null;
         $result = this.removeAppointment (appointmentID, appointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ManagementServer/HealthCareSystem/bookAppointment
       {
         String patientID = in.read_string ();
         ManagementServer.AppointmentType appointmentType = ManagementServer.AppointmentTypeHelper.read (in);
         String appointmentID = in.read_string ();
         String $result = null;
         $result = this.bookAppointment (patientID, appointmentType, appointmentID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // ManagementServer/HealthCareSystem/cancelAppointment
       {
         String patientID = in.read_string ();
         String appointmentType = in.read_string ();
         String appointmentID = in.read_string ();
         String $result = null;
         $result = this.cancelAppointment (patientID, appointmentType, appointmentID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // ManagementServer/HealthCareSystem/getAppointmentSchedule
       {
         String patientID = in.read_string ();
         String $result = null;
         $result = this.getAppointmentSchedule (patientID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // ManagementServer/HealthCareSystem/listAppointmentAvailability
       {
         String appointmentType = in.read_string ();
         String $result = null;
         $result = this.listAppointmentAvailability (appointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // ManagementServer/HealthCareSystem/swapAppointment
       {
         String patientID = in.read_string ();
         String oldAppointmentType = in.read_string ();
         String oldAppointmentID = in.read_string ();
         String newAppointmentType = in.read_string ();
         String newAppointmentID = in.read_string ();
         boolean $result = false;
         $result = this.swapAppointment (patientID, oldAppointmentType, oldAppointmentID, newAppointmentType, newAppointmentID);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ManagementServer/HealthCareSystem:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public HealthCareSystem _this() 
  {
    return HealthCareSystemHelper.narrow(
    super._this_object());
  }

  public HealthCareSystem _this(org.omg.CORBA.ORB orb) 
  {
    return HealthCareSystemHelper.narrow(
    super._this_object(orb));
  }


} // class HealthCareSystemPOA
