package ManagementServer;


/**
* ManagementServer/HealthCareSystemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ManagementServer.idl
* Monday, March 4, 2024 6:34:34 o'clock PM EST
*/

public interface HealthCareSystemOperations 
{
  String addAppointment (String appointmentID, ManagementServer.AppointmentType appointmentType, int capacity);
  String removeAppointment (String appointmentID, ManagementServer.AppointmentType appointmentType);
  String bookAppointment (String patientID, ManagementServer.AppointmentType appointmentType, String appointmentID);
  String cancelAppointment (String patientID, String appointmentID);
  String getAppointmentSchedule (String patientID);
  String listAppointmentAvailability (String appointmentType);
  boolean swapAppointment (String patientID, String oldAppointmentType, String oldAppointmentID, String newAppointmentType, String newAppointmentID);
} // interface HealthCareSystemOperations
